# Base16 Default Dark 256 - alacritty color config
# Chris Kempson (http://chriskempson.com)

# Default colors
[colors.primary]
background = '#181818'
foreground = '#d8d8d8'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#181818'
cursor = '#d8d8d8'

# Normal colors
[colors.normal]
black = '#181818'
red = '#ab4642'
green = '#a1b56c'
yellow = '#f7ca88'
blue = '#7cafc2'
magenta = '#ba8baf'
cyan = '#86c1b9'
white = '#d8d8d8'

# Bright colors
[colors.bright]
black = '#585858'
red = '#ab4642'
green = '#a1b56c'
yellow = '#f7ca88'
blue = '#7cafc2'
magenta = '#ba8baf'
cyan = '#86c1b9'
white = '#f8f8f8'

[[colors.indexed_colors]]
index = 16
color = "#dc9656"

[[colors.indexed_colors]]
index = 17
color = "#a16946"

[[colors.indexed_colors]]
index = 18
color = "#282828"

[[colors.indexed_colors]]
index = 19
color = "#383838"

[[colors.indexed_colors]]
index = 20
color = "#b8b8b8"

[[colors.indexed_colors]]
index = 21
color = "#e8e8e8"
